//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_StoryBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AD_Columns
    {
        public int ID { get; set; }
        public string adCompany { get; set; }
        public string adCompanyTel { get; set; }
        public string adPhoto { get; set; }
        public string adURL { get; set; }
        public string adRemarks { get; set; }
        public System.DateTime adCreateTime { get; set; }
    }
}
