//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_StoryBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleInfo
    {
        public ArticleInfo()
        {
            this.ArtComment = new HashSet<ArtComment>();
        }
    
        public int ID { get; set; }
        public string artNo { get; set; }
        public string Title { get; set; }
        public string artContent { get; set; }
        public System.DateTime artCreateTime { get; set; }
        public int artClsID { get; set; }
        public string uAccount { get; set; }
        public int artAuthority { get; set; }
        public int artHot { get; set; }
        public int artComCnt { get; set; }
        public string artDigest { get; set; }
    
        public virtual ICollection<ArtComment> ArtComment { get; set; }
        public virtual ArticleClass ArticleClass { get; set; }
    }
}
