//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_StoryBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PictureInfo
    {
        public PictureInfo()
        {
            this.PicComment = new HashSet<PicComment>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string ImgFile { get; set; }
        public System.DateTime picCreateTime { get; set; }
        public Nullable<int> picHot { get; set; }
        public int PicClsID { get; set; }
        public string uAccount { get; set; }
        public string picDescribe { get; set; }
    
        public virtual ICollection<PicComment> PicComment { get; set; }
        public virtual PictureClass PictureClass { get; set; }
    }
}
